services:
  db:
    container_name: "db"
    image: postgres:15.6-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

networks:
  custom:
    driver: bridge