services:
  db:
    container_name: "db"
    image: postgres:15.6-alpine3.18
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge